version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "We are in pre build phase"
      - apt-get update && apt-get -y install python3-pip python3-dev && python3 -m pip install --upgrade pip &&pip3 install --upgrade awscli
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.19.6/2021-01-05/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x ./kubectl
      - chmod +x ./aws-iam-authenticator
      - mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      - mv ./kubectl /usr/local/bin/kubectl
      - curl -sS --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
      - mv /tmp/eksctl /usr/local/bin
      - curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 > get_helm.sh
      - chmod 700 get_helm.sh
      - ./get_helm.sh
      - aws eks update-kubeconfig --kubeconfig ~/.kube/config --alias latest-peak-k8s01-eks --name latest-peak-k8s01-eks --region eu-west-1 --role-arn arn:aws:iam::122403041129:role/eks-cluster-deploy-role
  build:
    commands:
      - helm install k8s-web-hello mychart --namespace helm-deploy-test
  post_build:
    commands:
      - echo We are in post build phase
