version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "We are in pre build phase"
      - #!/bin/bash
      # - yum update -y
      - yum install -y jq sudo
      - sudo yum install git -y
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install && aws --version && rm -r ./aws
      - curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
      - curl -LO "https://dl.k8s.io/v1.25.0/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - sudo which helm
      # - export PATH=$PATH:/usr/local/bin
      # - export HELM_INSTALL_DIR="/usr/local/bin"
      - sudo chmod 777 ./get_helm.sh
      # - sudo ./get_helm.sh
      - sudo ls -lrt
      - sudo echo $PATH
      - sudo ls -lart /usr/local/bin
      # - sudo ln -s /usr/local/bin/helm /bin/helm
      - sudo mv /usr/local/bin/helm /usr/local/bin/helm3
  build:
    commands:
      - helm install --upgrade .
  post_build:
    commands:
      - echo We are in post build phase
