version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "We are in pre build phase"
      - #!/bin/bash
      # - yum update -y
      - yum install -y jq sudo
      - sudo yum install git -y
      # - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install && aws --version && rm -r ./aws
      - curl -LO "https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl"
      - curl -LO "https://dl.k8s.io/v1.25.0/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      # - export PATH=$PATH:/usr/local/bin
      - sudo ls -lrt
      - export HELM_INSTALL_DIR="/bin"
      - sudo ls -lrt
      - sudo chmod 700 ./get_helm.sh
      - sudo ls -lrt
      - sudo ./get_helm.sh || true
      - sudo ls -lrt
      - sudo echo $PATH
      - sudo ls -lart /usr/local/bin
      - sudo ln -s /usr/local/bin/helm /bin/helm
      - helm version
      - aws eks update-kubeconfig --name latest-peak-k8s01-eks --role-arn arn:aws:iam::122403041129:role/eks-cluster-admin-role --alias latest-dev-cluster
      # - sudo mv /usr/local/bin/helm /usr/local/bin/helm3
  build:
    commands:
      # - helm install --upgrade .
      - helm install k8s-web-hello mychart --namespace helm-deploy-test
  post_build:
    commands:
      - echo We are in post build phase
