version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo "Installing something"
  build:
    commands:
      - echo We are in pre build phase
  post_build:
    commands:
      - echo We are in post build phase
