version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo "We are in pre build phase"
      # Installing essential packages
      - yum update -y
      - yum install -y sudo
      - sudo yum install git curl -y
      # Installing/Updating AWS CLI
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip -q awscliv2.zip
      - sudo ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update && aws --version && rm -r ./aws
      # Installing kubectl latest version
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - curl -LO "https://dl.k8s.io/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl.sha256"
      - echo "$(cat kubectl.sha256)  kubectl" | sha256sum --check
      - sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      - kubectl version --client
      # Adding kube context of latest dev eks cluster
      - aws eks update-kubeconfig --name latest-peak-k8s01-eks --role-arn arn:aws:iam::122403041129:role/eks-cluster-deploy-role --alias latest-dev-cluster
      # checking if the context is working
      - kubectl get po
      # Installing Helm latest version
      - curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - sudo chmod 700 ./get_helm.sh
      - sudo ./get_helm.sh || true
      - helm version
      - sudo ls -lrt

  build:
    commands:
      - echo "Installing Helm chart..."
      - helm install k8s-web-hello mychart --namespace helm-deploy-test

  post_build:
    commands:
      - echo "All Done!!"
