apiVersion: v1
kind: Service
metadata:
  name: k8s-web-hello
spec:
  # We added this field afterwards. If not present, it defaults to CluserIP.
  type: LoadBalancer
  selector:
    app: k8s-web-hello
  ports:
  # Before, we didn't need target port, because we exposed the same port at which our node server was running(3000)
  # Now, lets expose the server(running at 3000), to some other port(say 3030)
  - port: 3030
    targetPort: 3000
